//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuestEaseHMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class billingdetl
    {
        public int bill_id { get; set; }
        public long id_proof { get; set; }
        public string name { get; set; }
        public int room_no { get; set; }
        public string room_type { get; set; }
        public System.DateTime check_in { get; set; }
        public System.DateTime check_out { get; set; }
        public int no_ofdays { get; set; }
        public long room_price { get; set; }
        public long total { get; set; }
        public Nullable<int> reserv_id { get; set; }
    
        public virtual reservdetl reservdetl { get; set; }
    }
}
