//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuestEaseHMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class receptionistdetl
    {
        public int r_id { get; set; }
        public string r_name { get; set; }
        public string r_phoneno { get; set; }
        public string r_address { get; set; }
        public string r_email { get; set; }
        public string r_username { get; set; }
        public string r_password { get; set; }
    }
}
