//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuestEaseHMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservdetl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reservdetl()
        {
            this.billingdetls = new HashSet<billingdetl>();
        }
    
        public int reserv_id { get; set; }
        public string cust_name { get; set; }
        public int room_no { get; set; }
        public string room_type { get; set; }
        public long room_price { get; set; }
        public long cust_idproof { get; set; }
        public System.DateTime checkin { get; set; }
        public System.DateTime checkout { get; set; }
        public int c_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billingdetl> billingdetls { get; set; }
        public virtual customerdetl customerdetl { get; set; }
    }
}
