//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuestEaseHMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class roomdetl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public roomdetl()
        {
            this.customerdetls = new HashSet<customerdetl>();
        }
    
        public int room_id { get; set; }
        public int room_no { get; set; }
        public string room_type { get; set; }
        public long room_price { get; set; }
        public string booked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customerdetl> customerdetls { get; set; }
    }
}
